### ISSUE TITLE
Azkaban3.76---Flow Trigger Schedule Plugin

### ISSUE THREAD

**Issue by AronChung** [AronChung/blog#80]
### 如何使用Flow Trigger插件？
1. 创建目录：`../azkaban-web-server/plugins/dependency/kafka`
2. 
```
cp ../az-flow-trigger-dependency-plugin/build/libs/az-flow-trigger-dependency-plugin-3.76.0.jar ../azkaban-web-server/plugins/dependency/kafka
cp ../az-flow-trigger-dependency-type/kafka-event-trigger/build/libs/kafka-event-trigger-3.76.0-fat.jar ../azkaban-web-server/plugins/dependency/kafka
cp ../az-flow-trigger-dependency-type/kafka-event-trigger/build/libs/kafka-event-trigger-3.76.0.jar ../azkaban-web-server/plugins/dependency/kafka
```

3. 在`../azkaban-web-server/plugins/dependency/kafka`中创建dependency.properties文件，并添加几个属性：
```
dependency.class=trigger.kafka.KafkaDependencyCheck
#dependency.classpath要求绝对路径
dependency.classpath=/Users/aronchung/IdeaProjects/lz-azkaban/azkaban-web-server/plugins/dependency/kafka/kafka-event-trigger-3.76.0-fat.jar
kafka.broker.url=127.0.0.1:9092
```

最终的目录结构为：
![image](https://user-images.githubusercontent.com/15808770/69109773-af053800-0ab3-11ea-87e0-f093fe20e37c.png)

4. 在web的azkaban.properties文件中，添加几个属性：
```
#配置flow trigger
azkaban.server.schedule.enable_quartz=true
azkaban.dependency.plugin.dir=/Users/aronchung/IdeaProjects/lz-azkaban/azkaban-web-server/plugins/dependency
org.quartz.dataSource.quartzDS.driver = com.mysql.jdbc.Driver
org.quartz.dataSource.quartzDS.URL = jdbc:mysql://127.0.0.1:3306/azkaban
org.quartz.dataSource.quartzDS.user = azkaban
org.quartz.dataSource.quartzDS.password = azkaban
org.quartz.threadPool.threadCount = 3
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.dataSource=quartzDS
```

===================到这里，Flow Trigger插件就配置完成了===================

### 使用方法
1. 在.flow文件中，使用trigger属性，例如：
```
trigger: 
  maxWaitMins: 2880
  schedule:
    type: cron
    value: 0 0/1 * * * ?
   
  triggerDependencies:
    - name: zcm_local
      type: kafka
      params:
        match: xyz
        topic: Zcm_local_topic
```
#### 其中，type的值要与目录dependency下的文件夹对应，如值为kafka，对应目录kafka；
match是Zcm_local_topic中，生产者发送的字符匹配，支持正则表达式。

2. 到这里就全部完成了，启动服务，上传脚本，随后可看到以下页面：
![image](https://user-images.githubusercontent.com/15808770/69110024-626e2c80-0ab4-11ea-9f82-8181da868486.png)
当kafka的Zcm_local_topic有匹配match的消息出现时，任务状态会变为`SUCCESS`，随即在executing页面能看到任务开始`RUNNING`

**Comment by super-sean** [comment]
nice

**Comment by cherful** [comment]
楼主您好，我在使用trigger中遇到一些，请求您的帮助。

问题： 
2022/08/11 19:02:00.023 +0800 ERROR [FlowTriggerService] [QuartzScheduler_Worker-2] [Azkaban] unable to create dependency context for trigger instance[id = 3388b5a7-6902-4304-9b07-0134135effbc]
java.lang.NullPointerException
	at azkaban.flowtrigger.FlowTriggerService.createDepContext(FlowTriggerService.java:135)
	at azkaban.flowtrigger.FlowTriggerService.createTriggerInstance(FlowTriggerService.java:148)
	at azkaban.flowtrigger.FlowTriggerService.startTrigger(FlowTriggerService.java:378)
	at azkaban.flowtrigger.quartz.FlowTriggerQuartzJob.execute(FlowTriggerQuartzJob.java:58)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2022/08/11 19:02:00.023 +0800 ERROR [FlowTriggerService] [QuartzScheduler_Worker-2] [Azkaban] unable to create dependency context for trigger instance[id = 3388b5a7-6902-4304-9b07-0134135effbc]
java.lang.NullPointerException
	at azkaban.flowtrigger.FlowTriggerService.createDepContext(FlowTriggerService.java:135)
	at azkaban.flowtrigger.FlowTriggerService.createTriggerInstance(FlowTriggerService.java:148)
	at azkaban.flowtrigger.FlowTriggerService.startTrigger(FlowTriggerService.java:378)
	at azkaban.flowtrigger.quartz.FlowTriggerQuartzJob.execute(FlowTriggerQuartzJob.java:58)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2022/08/11 19:02:00.024 +0800 ERROR [FlowTriggerService] [QuartzScheduler_Worker-2] [Azkaban] unable to create dependency context for trigger instance[id = 3388b5a7-6902-4304-9b07-0134135effbc]
java.lang.NullPointerException
	at azkaban.flowtrigger.FlowTriggerService.createDepContext(FlowTriggerService.java:135)
	at azkaban.flowtrigger.FlowTriggerService.createTriggerInstance(FlowTriggerService.java:148)
	at azkaban.flowtrigger.FlowTriggerService.startTrigger(FlowTriggerService.java:378)
	at azkaban.flowtrigger.quartz.FlowTriggerQuartzJob.execute(FlowTriggerQuartzJob.java:58)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
